services:
  db:
    image: postgres:16.4-bullseye
    container_name: atlas_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      timeout: "-1"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s
      timeout: 60s
      retries: 5
    restart : always

  pgadmin:
    image: dpage/pgadmin4
    container_name: atlas_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      timeout: "-1"
    networks:
      - app-network
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: atlas_frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    labels:
      timeout: "-1"
    networks:
      - app-network
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: atlas_backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=1
    labels:
      timeout: "-1"
    networks:
      - app-network
    restart: always
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge