# Generated by Django 5.1.4 on 2025-01-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas_backend", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="flag_answer",
        ),
        migrations.RemoveField(
            model_name="team",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="team",
            name="challenges",
            field=models.ManyToManyField(
                blank=True, to="atlas_backend.challenge"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("exited", "Exit"),
                    ("error", "Error"),
                ],
                default="exited",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="atlas_backend.team",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("team", "challenge")},
        ),
    ]
