# Generated by Django 5.1.4 on 2025-01-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='flag_answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='flag_submitted',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('exited', 'Exit'), ('error', 'Error')], default='stopped', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
