# Generated by Django 5.1.4 on 2025-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0003_rename_ssh_key_container_ssh_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$SU5DjeE6AYYJd1JZBIg6vN$bO/dupnbfpm0IC4oDJpdyIMMsS6+fEvO/zDL8PdWG/4=', max_length=128),
        ),
    ]
