# Generated by Django 5.1.4 on 2025-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0005_alter_challenge_category_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$GEqNqv7dXs1YJHVKrdKdUH$oL7MYaS5X8/JN9d4UMv0txqgCA3SA/VUe2p8MO1yn7I=', max_length=128),
        ),
    ]
