# Generated by Django 5.1.4 on 2025-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0007_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$qRxM6m4DlIou7W8W8ya1lg$K4DOcILMgUz7HdAJfEoUKz7kYTfEvDj8g7UuLaFcUcg=', max_length=128),
        ),
    ]
