# Generated by Django 5.1.4 on 2025-02-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0008_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$MHEiozzNDKNfqDiBqyaLt5$h6fHmpVt3KWYArZhdbLj/hcE5jRMiy7rvgIWlVxewKc=', max_length=128),
        ),
    ]
