# Generated by Django 5.1.4 on 2025-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0009_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Glo7NSL0iaNlnhyfgmkdN8$TV6BMVhzek11o2vH/2OmPI05o+kn/2r386rwHgG/Owo=', max_length=128),
        ),
    ]
