# Generated by Django 5.1.4 on 2025-02-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0010_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$M8I0Qznvi2xlvC9IgSZqNY$gIswkgXbcpN4/Itff8JURXmYYN1b6f3wXrKAaDIlRR4=', max_length=128),
        ),
    ]
