# Generated by Django 5.1.4 on 2025-03-20 07:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0011_alter_team_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='max_attempts_per_challenge',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_size',
        ),
        migrations.AddField(
            model_name='challenge',
            name='max_attempts',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9fkScQa5Yned5b5ERyju66$ZCIO/JV7QxiQXAF1UpwJ7qTh0WL4cSi2kkWZLjDTJtM=', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
