# Generated by Django 5.1.7 on 2025-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0011_alter_team_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='max_attempts_per_challenge',
        ),
        migrations.AddField(
            model_name='challenge',
            name='max_attempts',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='challenge',
            name='timeout',
            field=models.IntegerField(default=-1, help_text='Timeout in seconds for the challenge'),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$d4EOhymt8Hg7qiplhWeOCr$0wWGiG3D7kIwF3BIo+gBPeOpAjB+ENc58dN6tICLf4g=', max_length=128),
        ),
    ]
