# Generated by Django 5.1.7 on 2026-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atlas_backend", "0014_remove_team_description_alter_team_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$870000$rTdAGQyX07v4He5YzV0Igv$InO+U8+J1UqMI6/7alNs4j8Z5/qBgfAF29cRKdYxrGY=",
                max_length=128,
            ),
        ),
    ]
