# Generated by Django 5.1.7 on 2025-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0014_remove_team_description_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$5RVLhJoh9HUjbEpm63lHfJ$pYq3xqfLYslhWw7c1cv9Y2/mkOv0cFq55U3OxqmmvQ8=', max_length=128),
        ),
    ]
