# Generated by Django 5.1.7 on 2025-08-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0014_remove_team_description_alter_team_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Impossible')], default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$FCBOxGI5PPDw9HKduNNZQ1$qOV94RapNQK0ysbEUZGgOgpDg8BBOwRyPITLkMo8VNk=', max_length=128),
        ),
    ]
