# Generated by Django 5.1.7 on 2025-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0015_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$G0uhQppb7UWTGLPHEsYK67$J322lzPxXEmGjmhG4KpHa0/6QYeFJq2ua8v6DVboVE4=', max_length=128),
        ),
    ]
