# Generated by Django 5.1.7 on 2025-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0016_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$JHhOrxFqz9NDdEtu4NfOWP$kAuKP0HJ7XNCMPRYVy0x0P28bF2zq0FaaiC252E039g=', max_length=128),
        ),
    ]
