# Generated by Django 5.1.7 on 2025-08-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_backend', '0017_alter_team_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Atlas', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#000000', max_length=10)),
                ('secondary_color', models.CharField(default='#1f2937', max_length=10)),
                ('accent_color', models.CharField(default='#FB3E3C', max_length=10)),
                ('font_family', models.CharField(default='ui-sans-serif, system-ui', max_length=100)),
                ('timer_start', models.DateTimeField(blank=True, null=True)),
                ('timer_end', models.DateTimeField(blank=True, null=True)),
                ('custom_css', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$txo0aYo4N7BGqKIIITO6BR$R7xbYbHTwMLO41voOIMfOz3Mmq7PfOXg03zotV6ldrU=', max_length=128),
        ),
    ]
